title: Travel Impact Model
description: Travel Impact Model
baseurl: "" # the subpath of your site, e.g. /blog
url: "travelimpactmodel.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
